# -*- makefile -*-
obj-m += kexec_mod_$(ARCH).o
kexec_mod_$(ARCH)-y := machine_kexec_drv.o machine_kexec_compat.o
kexec_mod_$(ARCH)-y += idmap.o cpu-reset.o hyp-shim.o
kexec_mod_$(ARCH)-y += machine_kexec.o orig/relocate_kernel.o

ccflags-y := -I$(src)/ -fno-unwind-tables -fno-asynchronous-unwind-tables

clean-dirs := orig

$(obj)/orig :
	mkdir -p $@

$(obj)/orig/machine_kexec.c : | $(obj)/orig
	ln -sf $(KDIR)/arch/$(ARCH)/kernel/machine_kexec.c $@

$(obj)/orig/relocate_kernel.S : | $(obj)/orig
	ln -sf $(KDIR)/arch/$(ARCH)/kernel/relocate_kernel.S $@

$(obj)/machine_kexec.c :: $(obj)/orig/machine_kexec.c
